// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleScssNamespace {
  export interface IStyleScss {
    active: string;
    addInputWrapper: string;
    filterWrapper: string;
    todo: string;
    todoList: string;
    todoListItem: string;
    todoListItemCompleted: string;
  }
}

declare const StyleScssModule: StyleScssNamespace.IStyleScss;

export = StyleScssModule;
